### PR TITLE
Beat detection analyzer

### PR DESCRIPTION
**Pull request by alexdmiller**
This is a port of Minim's beat detection implementation (source [here](https://github.com/ddf/Minim/blob/v2.2.2/src/ddf/minim/analysis/BeatDetect.java)) to Processing Sound.

If this were to be merged, there is still some work to do to clean it up and add documentation. But I wanted to figure out if merging this into processing-sound is something people even want. Also, I'm not quite sure what the licensing implications are with this PR.

Thanks!

### CODE REVIEW

**Comment by kevinstadler** [comment]
That looks like great work, much appreciated! The original code is GPL-licensed which is compatible with this library's LGPL, we should probably just include an attribution ('based on ....') to the original author.

Regarding documentation, Processing's new web documentation pipeline should go live in the next few weeks, which will make the XML files in the `processing/processing-docs` repository obsolete, as all documentation will then be built directly from the JavaDoc comments in the library source code! If you were happy to add some basic documentation of the public methods you could check the format of the class/method comments in other analyzer classes e.g. [here](https://github.com/processing/processing-sound/blob/master/src/processing/sound/FFT.java). If not I hope I'd get around to it in the next couple of weeks when I package the code up to make a new library release...(which will also address some of #58)!

**Comment by alexdmiller** [comment]
@kevinstadler great, glad to hear this could be useful!

I will update this PR with attribution and JavaDoc documentation sometime within the next week (probably next weekend).

**Comment by alexdmiller** [comment]
I have updated this PR with JavaDoc comments as well as a Processing example. Let me know what you think!


https://user-images.githubusercontent.com/926408/104104404-ca557880-525c-11eb-8e4f-30072cbcff33.mov

**Comment by kevinstadler** [comment]
All looks good, do you have any license information about the sound wave included in the example?

**Comment by alexdmiller** [comment]
Sorry for the long delay to answer your simple question. I created the sound file and am happy to have it fall under whatever license governs the repository as a whole?

I added a comment attributing the beat detection code to minim. Let me know if you think that should look different.

**Comment by kevinstadler** [comment]
No worries, I think that all looks great! I'll hopefully get around to releasing a new version (and finally adding some proper attribution to contributors like yourself...) this week, thanks!

**Pull request merged**
